### ISSUE TITLE
image crate too old

### ISSUE THREAD

**Issue by 772** [8bittree/normal_heights#1]
I think the image crate need to be updated.

```
expected enum `image::dynimage::DynamicImage`, found enum `DynamicImage`
```

**Comment by 8bittree** [comment]
That's not an error I'm seeing. I did see some functions that were deprecated in image 0.23.14 and removed in 0.24- the usage of those has been replaced.

Are you still seeing that issue, and if so, what version of image are you using?

**Comment by 772** [comment]
I'm still seeing that issue, but maybe I'm just doing it wrong. This is my code.

```
fn main() {
    let img = image::open("default.png").unwrap();
    let normal_map = normal_heights::map_normals(&img); // Error.
}
```

```
[dependencies]
image = "0.24.5"
normal-heights = "0.1.2"
```

**Comment by 772** [comment]
Only happened because I used a different image version than this crate.

@8bittree: I'm still a bit new to the Rust ecosystem, but maybe it's worth using ```image = "0.24"``` instead of ```image = "0.24.5"``` e. g.  because there won't be breaking changes in image version 0.24.x. But I'm not sure myself.
